<?php

use Illuminate\Database\Seeder;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('sub_categories')->insert([
        ['name' => 'Surrounds',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today()],
        ['name' => 'Mats',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Cabinets',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Dart Sets',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Merchandising',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Apparel',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Dart Zone',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Electronic Collections',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Wallets/Cases',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Promo Items',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Points',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Budweiser',
        'top_category_id' => 1,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Steel Tips',
        'top_category_id' => 2,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Soft Tips',
        'top_category_id' => 3,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'World Championship',
        'top_category_id' => 4,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'International Championship',
        'top_category_id' => 4,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Players Soft Tip',
        'top_category_id' => 4,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Players',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Rhino',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Pear Poly',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Embossed',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Poly Kite',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Mega Standard',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Stealth',
        'top_category_id' => 5,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Prism',
        'top_category_id' => 6,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Nylon',
        'top_category_id' => 6,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Carbon Fibre',
        'top_category_id' => 6,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Aluminium',
        'top_category_id' => 6,
        'created_at' => today(), 
        'updated_at' => today() ],
        ['name' => 'Stealth',
        'top_category_id' => 6,
        'created_at' => today(), 
        'updated_at' => today() ],
      ]); 
    }
}
